### ISSUE TITLE
Last Week Tasks

### ISSUE THREAD

**Issue by SheenaGit** [sopra-fs22-group-17/RaveWave-client#121]
- [x] sopra-fs22-group-17/RaveWave-client#122
- [x] sopra-fs22-group-17/RaveWave-client#123
- [x] sopra-fs22-group-17/RaveWave-client#125
- [x] sopra-fs22-group-17/RaveWave-client#126
- [x] sopra-fs22-group-17/RaveWave-server#116
- [x] sopra-fs22-group-17/RaveWave-client#128
- [x] sopra-fs22-group-17/RaveWave-client#129
- [x] sopra-fs22-group-17/RaveWave-client#130
- [x] sopra-fs22-group-17/RaveWave-client#131
- [x] sopra-fs22-group-17/RaveWave-client#132
- [x] sopra-fs22-group-17/RaveWave-client#133
- [x] sopra-fs22-group-17/RaveWave-client#124
