### ISSUE TITLE
As a user I want to be able to have a QR-code generated after the game mode selection, in order that the other players can scan the QR-code and are joined/added to the same game room/lobby.

### ISSUE THREAD

**Issue by v4lentin1879** [sopra-fs22-group-17/RaveWave-client#36]
**Development Tasks**

- [x] sopra-fs22-group-17/RaveWave-client#6

- [x] sopra-fs22-group-17/RaveWave-client#5

- [x] sopra-fs22-group-17/RaveWave-client#7
 
**Acceptance Criteria:**

- [x] A QR-code is generated, the selected game mode cannot be started by another player with other parameters, users can only join the game mode

- [x] The generated QR-code shall correspond to the selected game mode with the selected parameters

- [x] The person who selected the game mode is the host of the game mode

- [x] Upon scanning of the QR code, players are added to the lobby
 
**Priority**: minor

**Comment by marcoleder** [comment]
a99253d5ea8d8a93adb1cc45386508063d18fda4
