### ISSUE TITLE
As a user I want to be able to navigate through the system in order to be able to play the game.

### ISSUE THREAD

**Issue by SheenaGit** [sopra-fs22-group-17/RaveWave-client#38]
**Development Tasks**

- [ ] sopra-fs22-group-17/RaveWave-client#20
- [ ] sopra-fs22-group-17/RaveWave-client#25
- [ ] sopra-fs22-group-17/RaveWave-client#37
- [ ] sopra-fs22-group-17/RaveWave-client#23
- [ ] sopra-fs22-group-17/RaveWave-client#22

**Acceptance Criteria:**

- [ ] The user shall be move from one page to the next

- [ ] The user should be guarded from visiting unwanted pages
