### ISSUE TITLE
As a user, I want to be able to register as a RaveWaver in order to not have to authenticate with Spotify repeatedly.

### ISSUE THREAD

**Issue by marcoleder** [sopra-fs22-group-17/RaveWave-client#59]
As a user, I want to be able to register as a RaveWaver in order to not have to authenticate with Spotify repeatedly.

Development tasks:
- [x] sopra-fs22-group-17/RaveWave-client#60
- [x] sopra-fs22-group-17/RaveWave-client#61
- [x] sopra-fs22-group-17/RaveWave-client#62
- [x] sopra-fs22-group-17/RaveWave-client#63
- [x] sopra-fs22-group-17/RaveWave-client#78
- [x] sopra-fs22-group-17/RaveWave-client#79
- [x] sopra-fs22-group-17/RaveWave-client#80
- [x] sopra-fs22-group-17/RaveWave-server#92
- [x] sopra-fs22-group-17/RaveWave-server#96
- [x] sopra-fs22-group-17/RaveWave-server#102
- [x] sopra-fs22-group-17/RaveWave-server#103
- [x] sopra-fs22-group-17/RaveWave-server#101
- [x] #119
- [x] #120

Acceptance criteria:
- [x] Users can register with their desired credentials (given that the username is not yet taken)
- [x] Users can login with their previously set credentials and leverage services only available to logged in users
- [x] Users which have already authenticated with Spotify shall not be requested to authenticate again
